#!/usr/bin/env bash
# This script installs Nginx, configures it to serve "Holberton School" on port 80.

# Update package list and install nginx
apt-get update -y
apt-get install nginx -y

# Create an index.html file with the required text
echo "Holberton School for the win!" > /var/www/html/index.html

# Start nginx service
service nginx start

